### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGridNode#24]
## Description
We need to rename this project slightly to fit [our new project naming standards](https://github.com/OpenMined/.github/issues/11).

**The new name for this repo should be:** PyGridNode
**The new release name for this repo should be:** openmined.gridnode

I have gone ahead and renamed the repo, but I will need someone else to be in charge of changing the release name. **With that said, if this repo doesn't have an official release, then this issue can be closed.**

If you have any questions about this issue, please comment here or message **@cereallarceny** on Slack.

**Comment by oudarjya718** [comment]
addressing

**Comment by oudarjya718** [comment]
I want to propose to change new release name 
New release name :- OpenGNode (pronounced "open jee node")

**Comment by cereallarceny** [comment]
Sorry, this issue has already been discussed and decided. It will be
PyGridNode.

**Comment by IonesioJunior** [comment]
@Benardi

**Comment by Benardi** [comment]
Yup I'll  take care of that

**Comment by oudarjya718** [comment]
Alright ! Great! 👍  :)
