### ISSUE TITLE
What direction would this PyGridNode's development go to?

### ISSUE THREAD

**Issue by xexiyong** [OpenMined/PyGridNode#29]
## Question
What direction would this PyGridNode's development go to?

## Further Information
I just saw several projects, gridNetwork, pygrid and this.  feels a little unclear, the PyGridNode contains the worker client functionality, and more  in the future?  is it suitable for our developer's customized code such as the terminal environment for collecting industrial sensor data?

**Comment by jmaunon** [comment]
Hi @xexiyong . I fully understand your question. We are discussing this points in slack as well, so if we reach a conclusion I will address here (Actually I prefer these discussiones here, but slack is more agile)

**Comment by jmaunon** [comment]
Hi @xexiyong .
After a Team discussion this is clearer, i will try to help you.
As you states, there are three repositories:

1. PyGrid. The funcionality of this repo will be moved to PyGridNetwork in coming months. This does not mean the repo will be removed. in fact it is planned to used it as a kind of submodules repo where each app could be considered as a microservice. See [asperathos](https://github.com/ufcg-lsd/asperathos) as example
2. PyGridNode. This repo is intented to be the responsible of data and computations. 
3. PyGridNerwork. The funcionality of PyGrid will be moved to this one.

As you see PyGrid is evolving quite fast!

**Comment by xexiyong** [comment]
ok, thx :)

**Comment by dwalker0044** [comment]
@jmaunon, thanks for the update. I appreciate things are moving quickly.

Do you know when the documentation will be updated to reflect the changes? As discussed on slack, tutorials such as [What is PyGrid Demo](https://blog.openmined.org/what-is-pygrid-demo/) no longer appear to work and it's not clear (at least to a newcomer like myself) what needs to be changed to make it work.

Keep up the good work, really excited by OpenMined projects. Happy to help with reviews and testing.

**Comment by dwalker0044** [comment]
nm just seen https://github.com/OpenMined/PyGridNetwork/issues/24

**Comment by jmaunon** [comment]
Hi. I cannot tell when (because I do not know) but asap, we have in mind that documentation is as important as the code.
